### ISSUE TITLE
Time of weather is incorrect

### ISSUE THREAD

**Issue by Johnnywick1** [WilliamsMata/weather-app#1]
Hi,

Great app but I think the current weather shows incorrect info. When I want to check weather for example city of Rome in your app there is a 17.5°C (current temp). But when I check this city on the other app (with the same source open-meteo) current temp shows 23°C. I think there is a 6 hour difference between what shoul it be and what is now. Check it by yourself. (here is the app https://scriptax.github.io/weather-app/ with open-meteo source)

Thank you

**Comment by WilliamsMata** [comment]
Thank you very much for reviewing my app, I was seeing the problem and it was a timezone problem, I fixed it and included some changes in today's forecast. Thank you again for your help in improving my app. I appreciate your feedback.

**Comment by Johnnywick1** [comment]
No problem. 

If you have time, I have a suggestion to improve your application.

1. In the "Air condition" section, you can add additional information such as: Humidity, Cloud Cover, Precipitation, Percipation Hours, Sunrise, Sunset, AQI, UV Index (which open-meteo gives such possibilities and is useful for users)

2. In the 7-DAY FORECAST section, you can make additional clicks on a given day and it will display the same information as in the TODAY'S FORECAST and AIR CONDITIONS sections for each day.

3. You can also add the local time for the city.
4. And a less important thing: you can enlarge the icons for hourly and daily forecasts (but this is my subjective opinion)


I have a few more suggestions, but that's enough for now
If you feel like it and you see that what I propose will make your application more attractive, you can do it. Only my suggestions.

Thanks again and best regards

**Comment by Johnnywick1** [comment]
Hello again,
Is it possible to change geolocation to more accurate? The open-meteo has possibility to find user geolocation more accurate. Look at this app: https://misterf1x.github.io/WeatherAPP/  Ipwhois.io is not so good and it's not free.

Thank you
